### ISSUE TITLE
✏️ [TASK]: Incorporate stuff from the template(s)

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/ansible-collection-infra#2]
### Task Description

```[tasklist]
### Related Work Items
```

**Comment by p-j-smith** [comment]
closing as the [template has been archived ](https://github.com/UCL-MIRSG/ansible-role-template) and I think we have everything we need from it (renovate config, pre-commit config, etc). Please re-open if not!

**Comment by paddyroddy** [comment]
I was probably referring to the main template
