### ISSUE TITLE
🐛 [BUG]: `Ensure postgresql storage subdirectory exists` fails if `volume` matches current setup

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/ansible-collection-infra#24]
### Bug Description

With `external_storage_drive: /storage/xnat`

When I use this collection. This step fails:
https://github.com/UCL-MIRSG/ansible-collection-infra/blob/1621fb1062ac2f06f2b1a082a175c5c003c48e54/roles/postgresql/tasks/main.yml#L61-L67

If, like you, I have https://github.com/UCL-MIRSG/ansible-collection-xnat/blob/4b3975734c4736ea9de2950a55037dc411643e30/tests/molecule/rocky9/molecule.yml#L23 of the form `./xnat-data:/storage/xnat`, but works if it is `./xnat-data/xnat:/storage/xnat`.

When the `mirsg.install_xnat` failed, I got onto the `xnat_db` container and wasn't able to make ny file or folder in `/storage/xnat`, however I could at the `/storage` level. This is likely because `mkdir` isn't recursive, you have to have the `-p` flag (@razekmh helped me debug this).

Can you look into either fixing this task step or change your https://github.com/UCL-MIRSG/ansible-collection-xnat/blob/main/tests/molecule/rocky9/molecule.yml - not sure how it is working for you currently.

### Acceptance Criteria

```[tasklist]
### Related Work Items
```

**Comment by razekmh** [comment]
Maybe using [recurse](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-recurse) would resolve the issue. 
<pre>
 - name: Ensure postgresql storage subdirectory exists 
   ansible.builtin.file: 
     path: "{{ postgresql_storage.storage_directory }}" 
     owner: "{{ postgresql.owner }}" 
     group: "{{ postgresql.group }}" 
     state: directory 
     mode: "0700"
     <b>recurse: true</b>
</pre>

**Comment by paddyroddy** [comment]
> @p-j-smith: Huh, where is your configuration? And what's the error you get?

With this in my docker-compose
```yaml
    volumes:
      - ./xnat-data:/storage/xnat
```
error
```
srr-ansible-1   | TASK [mirsg.infrastructure.postgresql : Ensure postgresql storage subdirectory exists] ***
srr-ansible-1   | fatal: [xnat_db]: FAILED! => {"changed": false, "msg": "There was an issue creating /storage/xnat/pgsql as requested: [Errno 2] No such file or directory: b'/storage/xnat/pgsql'", "path": "/storage/xnat/pgsql"}
```

If I change the volume to
```yaml
    volumes:
      - ./xnat-data:/storage/xnat
```
then I get past that step

**Comment by p-j-smith** [comment]
I think this might be related to another issue you were having with postgres, which was fixed by adding:

```bash
${USERNAME} ALL=\(ALL\) NOPASSWD:ALL
```
to your dockerfile. Since this change, I can't replicate the error you've reported here

**Comment by paddyroddy** [comment]
@p-j-smith spotted that my IP address was wrong for `xnat_web`. Fixing that, was enough for the problem to be solved 🤔 sorry for the noise!
