### ISSUE TITLE
✏️ [TASK]: Switch to official `rockylinux` docker image in tests

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/ansible-collection-infra#45]
### Task Description

Currently using `geerlingguy/docker-centos7-ansible:latest`, I think it would be better to use something like `rockylinux/rockylinux:9-ubi-init`, as used in the [SRR project](https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT).

```[tasklist]
### Related Work Items
```

**Comment by p-j-smith** [comment]
Closing as I think this was closed by https://github.com/UCL-MIRSG/ansible-collection-infra/pull/61, feel free to re-open if not
