### ISSUE TITLE
✨ [FEATURE]: Add role and playbook for upgrading postgresql

### ISSUE THREAD

**Issue by drmatthews** [UCL-MIRSG/ansible-collection-infra#64]
### Feature Description

Port the [role](https://github.com/UCL-MIRSG/XnatInstaller/tree/main/playbooks/roles/postgresql_upgrade) and [playbook](https://github.com/UCL-MIRSG/XnatInstaller/blob/main/playbooks/upgrade_postgres.yml) from XnatInstaller. Include similar playbook for use with OMERO.

### Definition of Done

This collection includes a role and playbooks for upgrading postgresql.

```[tasklist]
### Related Stories
```

```[tasklist]
### Related Tasks
```

**Comment by p-j-smith** [comment]
Closing as I think this was done in https://github.com/UCL-MIRSG/ansible-collection-infra/pull/71
