### ISSUE TITLE
Review nginx port variables

### ISSUE THREAD

**Issue by drmatthews** [UCL-MIRSG/ansible-collection-infra#65]
### Short Description

Currently there are two variables referring to upstream ports that are a little confusing:

https://github.com/UCL-MIRSG/ansible-collection-infra/blob/370891833ae00d7bfd46ba0d18ea5c416e810b95/roles/nginx/templates/nginx_reverse_proxy.j2#L14-L23

We should have a look to see if both are needed and if they are we should think of more descriptive names.

**Comment by p-j-smith** [comment]
Yeah I find them confusing too. The [previous variable names](https://github.com/UCL-MIRSG/ansible-collection-xnat/blob/1afe9524e7a5c6b477eef94e14b62236902ca95a/roles/nginx/templates/nginx.j2#L11-L20) were:

```
stream {
    upstream dicom {
        server localhost:{{ xnat_dicom_port }};
    }

    server {
        listen {{ dicom_port }};
        proxy_pass dicom;
    }
}
```

**Comment by HChughtai** [comment]
Deprecated due to #126
