### ISSUE TITLE
Add tests to make sure the container service is actually running

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/ansible-collection-infra#70]
### Short Description

Prior to https://github.com/UCL-MIRSG/ansible-collection-infra/pull/67, the container service wasn't actually working, but we had no idea. We could alleviate this with some kind of testing to check for a ping from the docker service, and even upload a sample image. An example of which can be seen here https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/15d77eb2d203e898685f11b2cf6bf1cabed9fa46/.github/workflows/playbooks.yml#L74-L100

**Comment by p-j-smith** [comment]
Yeah this would be a good first step. Ideally we'd have integration tests to create an XNAT project, upload some DICOM image, and run a container on them (this would also check the [path translation](https://wiki.xnat.org/ml/configure-the-container-service-plugin#ConfiguretheContainerServicePlugin-ConfigureContainerServiceHost(ForDocker-ComposeDistributions)) between the web and container service is set up correctly)
