### ISSUE TITLE
🙅 [PROBLEM]: Playbooks are co-dependent

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/ansible-collection-infra#72]
### Problem Description

The order of playbooks is essential, i.e. you can only install the container service after you've installed XNAT. Makes sense, but does it to the user?

### Acceptance Criteria

```[tasklist]
### Related Work Items
```

**Comment by p-j-smith** [comment]
Good point! I think it would make sense to combine the two (add `mirsg.infrastructure.install_container_service` to `mirsg.infrastructure.install_xnat`)
