### ISSUE TITLE
🙅 [PROBLEM]: `install_container_service` should check if `install_xnat` succeeded

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/ansible-collection-infra#73]
### Problem Description

`install_xnat` had failed for me, but I hadn't realised, this then meant that `install_container_service` was failing. There should be some kind of check at the start to see if XNAT is up.

### Acceptance Criteria

```[tasklist]
### Related Work Items
```

**Comment by p-j-smith** [comment]
A check would be good, or combine the two playbooks (https://github.com/UCL-MIRSG/ansible-collection-infra/issues/72#issuecomment-2016732440)
