### ISSUE TITLE
✏️ [TASK]: Is there much benefit of specifying `ansible_port`?

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/ansible-collection-infra#81]
### Task Description

https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html it defaults to `22` which is what we currently have. Do we have any ambitions of changing it? I wonder whether specifying it just adds unnecessary burden

```[tasklist]
### Related Work Items
```

**Comment by p-j-smith** [comment]
Not really, as you say it's the default so we can probably remove it
